# Generated by Django 5.0.6 on 2024-06-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
