# Generated by Django 5.0.6 on 2024-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_reparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='imagen',
            field=models.ImageField(default='default', upload_to='productos'),
            preserve_default=False,
        ),
    ]
